### ISSUE TITLE
代码转换成python3.X 就报错了，求3.x版本的SDK 

### ISSUE THREAD

**Issue by limxing** [tencentyun/qcloud-cos-sts-sdk#1]

**Comment by bradelement** [comment]
遇到了同样的问题。

解决方案：

把import urllib2 删掉
把所有print加括号

quote, reduce没有加上这两行
from urllib.request import quote
from functools import reduce

dict相关：
没有has_key, 改成 key in dict
没有iteritems, 改成items

str, bytes相关：
这个有点2 把hmac那一坨稍微改一下
key = bytes(self.secret_key, encoding='utf-8')
source = bytes(source, encoding='utf-8')
sign = hmac.new(key, source, hashlib.sha1).digest()
sign = base64.b64encode(sign)
sign = str(sign, encoding='utf-8').rstrip()

**Comment by bbbcs** [comment]
楼上正解，hmac那段需要手工改（+import base64），其他的 2to3 -w sts.py 就好了。
