### ISSUE TITLE
gradle项目引入加载不到jar包

### ISSUE THREAD

**Issue by fuuqiu** [tencentyun/qcloud-cos-sts-sdk#11]
方便提供一份gradle引入jar包的示例么,修改仓库地址和引入相应的jar包均提示找不到jar包

**Comment by bradyxiao** [comment]
@fuuqiu  compile 'com.tencent.cloud:cos-sts-java:3.0.3'

**Comment by bradyxiao** [comment]
- 使用 gradle 集成方式

	1) 在您的项目根目录下的 build.gradle 文件中添加 maven 仓库：

`	allprojects {
		repositories {
		     ...
		     // 添加如下 maven 仓库地址
		     maven {
			 url "https://dl.bintray.com/qcloud/maven-repo"
		     }
		 }
	}`

	2) 在应用的根目录下的 build.gradle 中添加依赖：

	`'compile 'com.tencent.cloud:cos-sts-java:3.0.3'`

**Comment by bradyxiao** [comment]
> 
> 
> 方便提供一份gradle引入jar包的示例么,修改仓库地址和引入相应的jar包均提示找不到jar包
使用 gradle 集成方式

1) 在您的项目根目录下的 build.gradle 文件中添加 maven 仓库：
      allprojects {
	repositories {
	     ...
	     // 添加如下 maven 仓库地址
	     maven {
		 url "https://dl.bintray.com/qcloud/maven-repo"
	     }
	 }
}

2) 在应用的根目录下的 build.gradle 中添加依赖：

compile 'com.tencent.cloud:cos-sts-java:3.0.3'

**Comment by FlickerMi** [comment]
我加了也引入不了。

```
repositories {
        mavenLocal()
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://dl.bintray.com/qcloud/maven-repo/' }
    }
```
