### ISSUE TITLE
哎  这什么文档啊  简直服了

### ISSUE THREAD

**Issue by yanzexu** [tencentyun/qcloud-cos-sts-sdk#13]
durationSeconds这个东西设置了一点用没有，？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by konakonall** [comment]
durationSeconds是密钥的超时时长，默认是30分钟，也就是30分钟后密钥会失效。
