### ISSUE TITLE
这Java版本的sdk，呃

### ISSUE THREAD

**Issue by bleehome** [tencentyun/qcloud-cos-sts-sdk#14]
能不能严肃点啊，java版本的sdk完全就是一个demo啊。。。

**Comment by konakonall** [comment]
@bleehome 我们有提供maven的安装方式呀

**Comment by shelwinnn** [comment]
![image](https://user-images.githubusercontent.com/1756397/62527493-d110dc80-b86d-11e9-90a9-304ce79d4f34.png)

完全赞同， 写死的 Region？？

**Comment by konakonall** [comment]
@shelwinnn 这里的Region是因为历史原因当时没有就近请求，马上会修改成按照设置的Region来请求。这里使用 Java SDK 的不便之处在哪里呢，方便我们更好的改进。

**Comment by konakonall** [comment]
Region 已经改成接口输入地域
