### ISSUE TITLE
为什么用python的sdk会报错‘cannot concatenate 'str' and 'dict' objects’

### ISSUE THREAD

**Issue by ZHLiu95** [tencentyun/qcloud-cos-sts-sdk#16]
我是直接下载了整个project然后修改了sts_demo.py中相关的id、key、bucket等。然后执行python sts_demo.py会报错‘cannot concatenate 'str' and 'dict' objects’。python2.7.5的环境

**Comment by ZHLiu95** [comment]
似乎是有个bug，在sys.py的第149行，当时间设置过大时会进入到这个异常中，然后这个print语句写的好像有问题，dict和str是不能直接拼接的。

**Comment by bradyxiao** [comment]
@ZHLiu95 嗯，这是一个bug ,已处理
