### ISSUE TITLE
腾讯的接口没有全局架构

### ISSUE THREAD

**Issue by Jijun** [tencentyun/qcloud-cos-sts-sdk#23]
腾讯的接口都是不同团队各自为政，一个cos接口搞出两套，咱就不能全局统筹整合一下吗？微信的接口也是，有的是xml格式，有的是json格式，我服了u。cos抄袭了七牛云，不过咱api是否也能抄下七牛云呢，七牛api是真心好用。
`
	<groupId>com.qcloud</groupId>
	<artifactId>cos_api</artifactId>
`
`
	 <groupId>com.tencent.cloud</groupId>
	 <artifactId>cos-sts-java</artifactId>
`

**Comment by konakonall** [comment]
@Jijun 你好，是这样的，cos的底层架构经过了技术变革，所有SDK也有一些版本迭代。不过这两个SDK的功能是不一样的哈：cos_api 这个已经是较老的 SDK了。

**Comment by konakonall** [comment]
@Jijun 你好，是这样的，cos的底层架构经过了技术变革，所有SDK也有一些版本迭代。不过这两个SDK的功能是不一样的哈：
1. cos_api 是 封装 COS API 的 SDK，不过是很老的版本了，建议使用 https://github.com/tencentyun/cos-java-sdk-v5 代替。
2. cos-sts-java 是获取临时密钥的 SDK，这是腾讯云的另外一个底层服务，密钥可以用来使用 COS SDK 访问 COS 服务。
