### ISSUE TITLE
PHP包没有命名空间就算了，自动加载还是psr-0

### ISSUE THREAD

**Issue by Trient** [tencentyun/qcloud-cos-sts-sdk#24]
"autoload": {
      "psr-0": {
        "php\\": "sts/"
     }
    }

**Comment by konakonall** [comment]
后续会优化，谢谢你的意见

**Comment by Jian881219** [comment]
> 后续会优化，谢谢你的意见

过去这么久了还没优化啊

**Comment by Attax** [comment]
> 后续会优化，谢谢你的意见

无法自动加载

**Comment by konakonall** [comment]
请用3.0.2版本
