### ISSUE TITLE
dotnet 版SDK报资源错误

### ISSUE THREAD

**Issue by VincentWong0305** [tencentyun/qcloud-cos-sts-sdk#25]
STSClient.cs文件中，在getPolicy 有一段代码：
 foreach (string action in allowActions) {
                Dictionary<string, string> dic = new Dictionary<string, string>();
                dic.Add("action", action);
                dic.Add("effect", "allow");

                string[] splitParts = bucket.Split('-');
                string appId = splitParts[splitParts.Length - 1];
                string bucketName = bucket.Substring(0, bucket.Length - appId.Length - 1);
                if (!allowPrefix.StartsWith("/")) {
                    allowPrefix = "/" + allowPrefix;
                }
                dic.Add("resource", string.Format("qcs::cos:{0}:uid/{1}:{2}{3}",
                    region, appId, bucketName, allowPrefix));
                states.Add(dic);
            }
bucketName 是截取掉ID之后的存储桶名称，测试生成凭证的时候会报错，实际上需要用到完整的存储桶名称，把代码
  dic.Add("resource", string.Format("qcs::cos:{0}:uid/{1}:{2}{3}",
                    region, appId, bucketName, allowPrefix));
替换成:
  dic.Add("resource", string.Format("qcs::cos:{0}:uid/{1}:{2}{3}",
                    region, appId, bucket, allowPrefix));
最后成功获取临时凭证。

**Comment by konakonall** [comment]
@VincentWong0305 SDK 接受的参数是需要带 APPID 的 bucket 名称，而 policy 规则这里是需要不带 AppID 的，检查下是否外层传的参数有误

**Comment by VincentWong0305** [comment]
> @VincentWong0305 SDK 接受的参数是需要带 APPID 的 bucket 名称，而 policy 规则这里是需要不带 AppID 的，检查下是否外层传的参数有误
@konakonall 
我是按照使用示例写的测试代码：
`public static string GetCredential()
        {
            Dictionary<string, object> values = new Dictionary<string, object>();

            string bucket = ConfigurationHelper.GetValue("cos:bucketName");  // 您的 bucket
            string region = ConfigurationHelper.GetValue("cos:region");  // bucket 所在区域
            string allowPrefix = "*"; // 这里改成允许的路径前缀，可以根据自己网站的用户登录态判断允许上传的具体路径，例子： a.jpg 或者 a/* 或者 * (使用通配符*存在重大安全风险, 请谨慎评估使用)
            string[] allowActions = new string[] {  // 允许的操作范围，这里以上传操作为例
                "name/cos:*"
            };

            string secretId = ConfigurationHelper.GetValue("cos:SecretId"); // 云 API 密钥 Id
            string secretKey = ConfigurationHelper.GetValue("cos:SecretKey"); // 云 API 密钥 Key

            values.Add("bucket", bucket);
            values.Add("region", region);
            values.Add("allowPrefix", allowPrefix);
            values.Add("allowActions", allowActions);
            values.Add("durationSeconds", 1800); // 要申请的临时密钥最长有效时间，单位秒，最大可设置 7200

            values.Add("secretId", secretId);
            values.Add("secretKey", secretKey);

            string credential = STSClient.genCredential(values);
            return credential;
        }`

其中 bucket 值是带上了AppId的，如果是Policy 规则不带上AppID的话，结果是报错，错误信息为：
发生异常: CLR/TencentCloud.Common.TencentCloudSDKException
“TencentCloud.Common.TencentCloudSDKException”类型的异常在 System.Private.CoreLib.dll 中发生，但未在用户代码中进行处理: 'code:InvalidParameter.ResouceError message:[QC_STS] resource error '
   在 TencentCloud.Common.AbstractClient.<InternalRequest>d__31.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 TencentCloud.Sts.V20180813.StsClient.<GetFederationToken>d__6.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

然后我尝试着在对象存储桶使用图形手动配置策略，得到的策略语法是：
`{

  "Statement": [

    {

      "Action": [

        "name/cos:*"

      ],

      "Effect": "Allow",

      "Principal": {

        "qcs": [

          "qcs::cam::anyone:anyone"

        ]

      },

      "Resource": [

        "qcs::cos:ap-guangzhou:uid/1257042612:kom-1257042612/*"

      ]

    }

  ],

  "version": "2.0"

}`
这里语法的Resource是带上了APPID的。

**Comment by konakonall** [comment]
问题已修复，请使用 3.0.1版本
