### ISSUE TITLE
文档里写的getPolicy使用例子问题

### ISSUE THREAD

**Issue by putao520** [tencentyun/qcloud-cos-sts-sdk#30]
实测getPolicy必须带bucket和region,但是带了那2属性出来的权限再计算出的临时授权给到前端,所有的接口都是403!
所以最好的办法就是别用getPolicy构造授权权限结构,自己手写!!!

**Comment by konakonall** [comment]
403请麻烦检查一下申请的资源跟最终请求的资源是否是一致的，如果还有问题，可以发 requestId 出来看看。
