### ISSUE TITLE
sts_client_test.py request_sts()服务端报错

### ISSUE THREAD

**Issue by cwlseu** [tencentyun/qcloud-cos-sts-sdk#35]
Hi，你好！测试python sdk 的demo中的sts_client_test.py request_sts()
服务端程序报错如下：
Exception: ("result: {u'RequestId': u'1167ba7c-f4e5-4b36-9bfe-80b3a64a86fa', u'Error': {u'Message': u'The provided credentials could not be validated. Please check your signature is correct.', u'Code': u'AuthFailure.SignatureFailure'}}", KeyError('ExpiredTime',))
服务端成secretkey和secretid都已换成自己申请的了。
request_sts2()是没有问题。服务器端修改方法和request_sts一致。
请问这是什么原因呢？

**Comment by konakonall** [comment]
这个服务端只是示例，建议还是用自己的逻辑实现。可以查看demo里面的例子。
