### ISSUE TITLE
DotNet Framework 4.7.2获取临时令牌报错，非dotnet Core

### ISSUE THREAD

**Issue by sonofmagic** [tencentyun/qcloud-cos-sts-sdk#36]
错误信息：

TencentCloud.Common.TencentCloudSDKException:“code:InvalidParameter.GrantOtherResource message:[QC_STS] cant grant other resource ”

两次尝试都报此错误:
1.nuget: Tencent.QCloud.Cos.Sts.Sdk 3.0.1
2.直接github复制Master 的STSClient源码，放进源文件跑

**Comment by konakonall** [comment]
@sonofmagic 是否有返回得 requestId，可以发我看看

**Comment by konakonall** [comment]
确认下请求的资源跟使用的临时密钥的身份是否一致
