### ISSUE TITLE
sts.php 文件 在linux上会识别大小写 导致类找不到

### ISSUE THREAD

**Issue by leizihui** [tencentyun/qcloud-cos-sts-sdk#38]
文件名 sts.php   类名 STS  当使用 use QCloud\COSSTS\STS引入时  在mac和win上没问题 ，再linux上就会出现找不到类

**Comment by kskan** [comment]
+1,部署的时候心态炸了

**Comment by konakonall** [comment]
感谢反馈，3.0.3已修复
