### ISSUE TITLE
没有golang版本的sdk吗？

### ISSUE THREAD

**Issue by likun123687** [tencentyun/qcloud-cos-sts-sdk#4]
如题

**Comment by konakonall** [comment]
暂时没有golang，未来可以加上

**Comment by alpha-baby** [comment]
我现在是使用golang 做的后端服务如果需要给前端临时密码，需要怎么解决，

**Comment by konakonall** [comment]
@alpha-baby 建议自己实现签名算法和请求过程，可以参考文档https://cloud.tencent.com/document/product/598/33416

**Comment by konakonall** [comment]
golang SDK 已支持
