### ISSUE TITLE
how to set proxy？

### ISSUE THREAD

**Issue by Leibosite** [tencentyun/qcloud-cos-sts-sdk#44]
nodejs 版本的可以设置proxy java版本的怎么设置代理呢？

**Comment by Leibosite** [comment]
![image](https://user-images.githubusercontent.com/11767115/91037351-72b2c980-e63b-11ea-9266-d80e8633db09.png)
example中看到了这样实现，但感觉还是作为params 会更好。希望加上proxy这个参数。

**Comment by konakonall** [comment]
Node.js 支持传 proxy 参数的，可以在 Config 里面设置，可以查看 https://github.com/tencentyun/qcloud-cos-sts-sdk/blob/master/nodejs/demo/demo.js。Java 因为需要在虚拟机层面设置，所以设置到 System 参数里面。
