### ISSUE TITLE
python sdk生成的签名无法和cos-wx-sdk-v5中的示例配合使用吗？

### ISSUE THREAD

**Issue by nileinl** [tencentyun/qcloud-cos-sts-sdk#5]
使用此sdk生成的签名，与https://github.com/tencentyun/cos-wx-sdk-v5中的示例无法配合使用吗？
即使返回的是小写
data.credentials.tmpSecretId = data.credentials.tmpsecretid
data.credentials.tmpSecretKey = data.credentials.tmpsecretkey
data.credentials.sessionToken = data.credentials.token
COS也会返回ACCESS DENIED

**Comment by konakonall** [comment]
@nileinl 1. 和 cos-wx-sdk-v5 可以配合使用的，这里出现 ACCESS DENIED 看下是不是密钥的权限和请求的资源不匹配；
2. readme.md 这里说的不太匹配是哪里？调用方式可以看下 sts_demo.py 示例文件。
