### ISSUE TITLE
是否需要其他语言的 pr？

### ISSUE THREAD

**Issue by scottming** [tencentyun/qcloud-cos-sts-sdk#54]
写了一个 elixir 的版本，我们公司生产环境有在使用，需要的话，我可以提交 pr 到这边，如果需要改动，可以提建议

scottming/qcloud_cos_sts
https://github.com/scottming/qcloud_cos_sts

**Comment by konakonall** [comment]
@scottming 你好，非常感谢，因为我们目前没有懂 elixir 的同学，我这边会把你的 repo 链接到 README 里面，供其他开发者参考。
