### ISSUE TITLE
获取 sts  一直报AuthFailure.SignatureFailure

### ISSUE THREAD

**Issue by a852882874** [tencentyun/qcloud-cos-sts-sdk#60]
![image](https://user-images.githubusercontent.com/25943026/133190820-1319cd6a-621d-4dd0-9368-e3c22cd8bdbe.png)

**Comment by a852882874** [comment]
这是我的代码，完全是按照例子上面复制的
![image](https://user-images.githubusercontent.com/25943026/133190948-986c221d-1a57-4043-baa1-3cb155cc3ec8.png)

**Comment by tuuna** [comment]
![image](https://user-images.githubusercontent.com/9778380/133195995-a92a69a8-bc30-42df-aef6-38c9ca14d14c.png)
这个domain不应该填cos域名哈

**Comment by a852882874** [comment]
@tuuna 是写死的sts.tencentcloudapi.com吗

**Comment by tuuna** [comment]
是的，你可以看一下这边的具体写法

**Comment by tuuna** [comment]
https://github.com/tencentyun/qcloud-cos-sts-sdk/blob/master/php/demo/sts_test.php

**Comment by tuuna** [comment]
这边的domain指的是sts的服务域名，不是cos哈

**Comment by a852882874** [comment]
@tuuna 谢谢了哈，可以了

**Comment by tuuna** [comment]
@a852882874 不客气
