### ISSUE TITLE
能否设置将返回服务器时间作为签名的开始时间？

### ISSUE THREAD

**Issue by huangyanting** [tencentyun/qcloud-cos-sts-sdk#7]

**Comment by carsonxu** [comment]
COS用什么SDK？

**Comment by huangyanting** [comment]
Java

**Comment by konakonall** [comment]
请问需求是什么？现在返回的开始时间是通过计算得到的准确时间。

**Comment by huangyanting** [comment]
返回服务器时间作为签名的开始时间，用来避免由于用户手机本地时间偏差过大导致的签名不正确。

**Comment by carsonxu** [comment]
如果手机使用了 cos-js-sdk-v5 可以配置存储桶 CORS 的 ExposeHeader 增加 Date。就会自动校正时间。

**Comment by huangyanting** [comment]
能否从客户端传入客户端时间戳，服务端根据这个开始时间去定临时密钥

**Comment by carsonxu** [comment]
是否在用 cos-js-sdk-v5 上传文件？实例化的时候传入 SystemClockOffset 参数就可以，是偏移值，单位毫秒

**Comment by konakonall** [comment]
@huangyanting 现在SDK返回的startTime，就是服务器的开始时间。客户端如果时间有偏差，可以做本地校准。
